name: Build and Run

on: [push, pull_request]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1

    - name: Run tests and collect coverage
      run: dotnet test ./Sender/SensorSender/SensorSenderTests/SensorSenderTests.csproj --collect:"XPlat Code Coverage"

    - name: Install coverage report generator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool

    - name: Make coverage report
      run: reportgenerator "-reports:Sender\SensorSender\SensorSenderTests\TestResults\*\*.xml" "-targetdir:coverage"
    
    - name: Create coverage artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: coverage
        retention-days: 21
    
    - name: Run project
      run:  dotnet run --project ./Sender/SensorSender/SensorSender/SensorSender.csproj